# Generated by Django 4.0.1 on 2022-01-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USERS',
            new_name='MYUSERS',
        ),
    ]
