# Generated by Django 4.0.1 on 2022-01-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_users_myusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MYUSERS',
            new_name='ahmedd',
        ),
    ]
