# Generated by Django 4.0.1 on 2022-01-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_myusers_ahmedd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ahmedd',
            new_name='MYUSERS',
        ),
    ]
