# Generated by Django 4.0.1 on 2022-01-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_ahmedd_myusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MYUSERS',
            new_name='MYUSERSS',
        ),
    ]
