# Generated by Django 4.0.1 on 2022-01-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_intake_delete_myuserss_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intake',
        ),
    ]
