# Generated by Django 4.0.1 on 2022-01-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
