# Generated by Django 4.0.1 on 2022-01-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser_Register',
            new_name='Register',
        ),
    ]
