# Generated by Django 4.0.1 on 2022-01-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rename_myuser_register_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
